apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - port: 8888
      targetPort: 8888

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend-app
spec:
  selector:
    app: frontend-app
  ports:
    - port: 5173
      targetPort: 5173

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo-db
spec:
  selector:
    app: mongo-db
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP